### ISSUE TITLE
Bug: Elasticsearch 5.6 removed from Homebrew

### ISSUE THREAD

**Issue by zcuric** [MarcoFaul/valetPlusReforged#1]
Hi, great fork! Hope you will continue to update it! 

Same bug as described here: https://github.com/weprovide/valet-plus/issues/513

Simple fix is to set default version to be es@7.8.

**Comment by MarcoFaul** [comment]
Thanks @zcuric. I will update it in the upcoming days.

**Comment by llinards** [comment]
> Hi, great fork! Hope you will continue to update it!
> 
> Same bug as described here: [weprovide/valet-plus#513](https://github.com/weprovide/valet-plus/issues/513)
> 
> Simple fix is to set default version to be es@7.8.

Hi! Can you please help how to change default version of ES?
